# Site settings
author: Paul Holmes
title: My blog title!
header-img: img/home-bg.png
email: paulholmes1993@gmail.com
copyright_name: Paul Holmes
description: > # this means to ignore newlines until "baseurl:"
  My blog for FlatIron Software Engineering Program
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  paulholmes1993

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
